# Copyright (c) 2025 TheEmbersOfTwilight
# Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0) for code.
# Creative assets and prose in this repository are licensed under CC BY-NC-SA 4.0 unless otherwise noted.
# See LICENSE-AGPLv3 and LICENSE-CC-BY-NC-SA-4.0 in the repository root for full license texts.
import time
import sys
question = "What do you say?"
choice = "What do you do?"
def type_text(text, delay=0.05):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()  
        time.sleep(delay)
Razor=False
Wand=False
door1=False
potion1=False
Apprentice=False
timewasted=False
scars=False
flowers_collected=False
type_text("When you are given a choice, type the number associated with the option you would like to choose")
print()
type_text("Have a good experience")
print()
time.sleep(5)
type_text("You awaken in a dark, damp room on a grimy bed")
time.sleep(1)
print()
type_text("You see a shelf on the opposite side of the room from where you currently are.")
time.sleep(1)
print()
type_text("As you get up from the bed, you see that it is being held up by chains connected to the wall.")
time.sleep(1)
print()
type_text("You also see that one wall of the room is made of metal bars.")
time.sleep(1)
print()
while Wand == False:
    type_text(choice)
    time.sleep(1)
    print()
    print("1. Look through the bars")
    time.sleep(1)
    print("2. Look at the shelf")
    time.sleep(1)
    print("3. Inspect the bed")
    choice1=input()
    if choice1 == "1":
        type_text("You see many cells along the hall on the other side of the bars.")
        print()
        time.sleep(1)
        type_text(choice)
        time.sleep(1)
        print()
        print("1. Call out")
        time.sleep(1)
        print("2. Go back")
        choice2 = input()
        if choice2 == "1": 
            type_text("You call out down the empty halls and get no response")
            time.sleep(1)
            print()
            type_text("You walk back into the cell")
            print()
            time.sleep(1)
            continue
        else: 
            type_text("You walk back into the cell")
            print()
            time.sleep(1)
            continue
    elif choice1 == "2": 
        if Razor == True:
                type_text("You look at the shelf and see nothing of interest, you walk back into thhe middle of the cell")
                print()
                time.sleep(1)
                continue
        else:
            type_text("You look at the shelf and see a dull, old style razor")
            time.sleep(1)
            print()
            type_text(choice)
            time.sleep(1)
            print()
            print("1. Pick up the razor")
            time.sleep(1)
            print("2. Leave it")
            choice3=input()
            if choice3 == "1":
                time.sleep(1)
                type_text("You pick up the razor and walk back to the middle of the cell")
                print()
                Razor=True
                continue
            else:
                type_text("You leave it and walk back to the middle of the cell")
                print()
                continue
    elif choice1 == "3":
        type_text("You inspect the bed closer and see a compartment hidden under the mattress")
        print()
        time.sleep(1)
        type_text("In the compartment you see a stick that tapers near the end, it has complex designs carved into it")
        print()
        time.sleep(1)
        type_text("You feel an aura of energy emanating from it and your fingers tingle as you hold it")
        print()
        time.sleep(1)
        type_text("You walk back into the middle of the cell")
        print()
        time.sleep(1)
        Wand=True
type_text("You now see a silhouette of a door on the wall next to the bed")
time.sleep(1)
while door1 == False:
    print()
    type_text(choice)
    print()
    time.sleep(1)
    print("1. Inspect the silhouette")
    time.sleep(1)
    print("2. Inspect the stick")
    choice4=input()
    if choice4 == "2":
        type_text("You inspect the stick and see that its designs are reminiscent of those you have seen in drawings of wands in fantasy books")
        time.sleep(1)
        print()
        continue
    elif choice4 == "1":
        type_text("You inspect the silhouette and see that there is a small hole within it that would fit the stick")
        print()
        time.sleep(1)
        type_text("You stick one end of the stick into the hole, it does not work")
        print()
        time.sleep(3)
        type_text("A few seconds later you realize it must be the other side that works, then stick that end in")
        print()
        time.sleep(1)
        type_text("The door swings open and you walk through")
        print()
        time.sleep(1)
        door1=True
    else:
        continue
type_text("You see a flash of light and your vison goes dark")
print()
time.sleep(3)
type_text("You awake from whatever has affected you, you have no idea how long you've been out but it feels as though it has been a while")
time.sleep(1)
print()
type_text("You see that you are in a room filled with books and beakers of all sorts, many of the beakers are filled with colorful liquids, while others are empty")
print()
time.sleep(1)
while potion1 == False:
    type_text(choice)
    print()
    time.sleep(1)
    print("1. Inspect the books")
    time.sleep(1)
    print("2. Inspect the beakers")
    time.sleep(1)
    choice5=input()
    if choice5 == "1":
        type_text("You take a closer look at the books and see a few of interest")
        time.sleep(1)
        print()
        print("The Secrets of Divination")
        time.sleep(1)
        print("The Sorcerer's Handbook of Draughts")
        time.sleep(1)
        print("How To Aid and Keep Thy Friends Forever")
        time.sleep(1)
        type_text("You decide against taking any of them as you feel a strange aura around them")
        print()
        time.sleep(1)
        continue
    elif choice5 == "2":
        type_text("You look closely at the beakers and see that one has a design on the glass identical to the one on the stick")
        print()
        time.sleep(1)
        type_text("You grab the beaker and pocket it, then hear a strange noise just a few moments later")
        print()
        time.sleep(3)
        potion1=True
    else:
        continue
type_text("You see a tall, robed figure approach you and loudly bellow")
print()
time.sleep(1)
type_text('"What are you doing in my sanctum?"')
print()
time.sleep(1)
type_text(question)
time.sleep(1)
print()
print("1. I'm lost and found this place")
time.sleep(1)
print("2. I'm your new apprentice")
choice6=input()
while Apprentice == False:
    if choice6 == "1":
        type_text('"How did you find this place, then? Did you come here from the prison?')
        print()
        time.sleep(1)
        Apprentice=True
    else:
        type_text('"I do not remember hiring a new apprentice"')
        print()
        type_text('"You are an imposter!"')
        print()
        time.sleep(1)
        type_text("He chants in a language you cannot understand and you feel light headed, you fall and your mind goes blank.")
        print()
        type_text("Game Over")
        print()
        sys.exit()
type_text('"Well then, I will help you for a short while. But you will have to assist for a time."')
print()
time.sleep(1)
type_text("The man walks you to a small room down a hall that appears as he walks over to the wall where he came from")
print()
time.sleep(1)
type_text("Inside the room is a small bed with what appears to be a down mattress")
print()
time.sleep(1)
type_text("There is also a side table next to the bed and a dresser on the opposite wall")
print()
time.sleep(1)
type_text('"Get some rest, and come talk to me in the morning"')
print()
time.sleep(1)
type_text("You lie down on the bed and quickly fall asleep")
print()
time.sleep(3)
type_text("You awake the next morning feeling refreshed")
print()
time.sleep(1)
type_text("You get up from the bed and walk out into the main room where the robed figure was")
print()
time.sleep(1)
type_text("You see that he is busy mixing a potion at a large table covered in beakers and books")
print()
time.sleep(1)
type_text("He looks up as you enter and speaks")
print()
time.sleep(1)
type_text('"Ah, you are awake. Good, I have a task for you."')
print()
time.sleep(1)
type_text('"I need you to gather some ingredients for a potion I am working on."')
print()
time.sleep(1)
type_text('"First, go to the forest outside and gather some moonshade flowers."')
print()
time.sleep(1)
type_text('"Next, go to the river and collect some water from the deepest part."')
print()
time.sleep(1)
type_text('"Finally, return here and I will show you how to make the potion."')
print()
time.sleep(1)
type_text("He hands you a small bag and a vial")
print()
time.sleep(1)
type_text("He points you towards a door that appears on the wall as he gestures")
print()
time.sleep(1)
type_text('"Go through there to reach the forest."')
print()
time.sleep(1)
type_text("You walk through the door and find yourself next to a tree in a dense forest, with a dilapidated stone building off in the distance")
print()
time.sleep(1)
type_text("It appears to be the building that you awoke in earlier")
print()
time.sleep(1)
type_text("You feel a strange pull towards a clearing deeper in the forest")
print()
time.sleep(1)
type_text("You walk towards the clearing, feeling more and more drawn to it with each step")
print()
time.sleep(1)
type_text("As you approach the clearing, the pull suddenly fades away")
print()
time.sleep(1)
type_text("In the center of the clearing, you see a patch of glowing flowers")
print()
time.sleep(1)
type_text("You walk over to the flowers and see that they are indeed moonshade flowers")
print()
time.sleep(1)
type_text("You move closer and inspect them closely")
print()
time.sleep(1)
type_text("Their stems seem to be incredibly thick and sturdy, almost like vines")
print()
time.sleep(1)
type_text("You get the feeling that you cannot pick them without using some sort of sharp object or ripping them out by the roots")
print()
time.sleep(1)
type_text(choice)
print()
time.sleep(1)
print("1. Pick the flowers")
time.sleep(1)
print("2. Leave empty handed")
time.sleep(1)
choice7=input()
if choice7 == "1":
    if Razor == True:
        type_text("You remember the razor you picked up earlier")
        print()
        time.sleep(1)
        type_text("You use the razor to carefully cut the flowers from their stems, being careful not to damage them")
        print()
        time.sleep(1)
        type_text("You gather a small bouquet of the flowers and head back towards the stone building")
        print()
        time.sleep(1)
        flowers_collected=True
    else:
        type_text("You try to pick the flowers by hand, but their stems are too thick and sturdy to break")
        print()
        time.sleep(1)
        type_text("After several frustrating minutes, you are finally able to rip a few flowers free")
        print()
        time.sleep(1)
        timewasted=True
        flowers_collected=True
elif choice7 == "2":
    type_text("You decide to leave the flowers alone")
    print()
    time.sleep(1)
    flowers_collected=False
type_text("You head towards the stone building")
print()
time.sleep(1)
type_text("It has a similar pull to the clearing, but not as strong")
print()
time.sleep(1)
type_text("As you approach the building, you see that there is a small river running alongside it")
print()
time.sleep(1)
type_text("You walk over to the river and see that it is quite deep in the center")
print()
time.sleep(1)
type_text("You wade into the river, thinking about how this must be the river the robed figure mentioned")
print()
time.sleep(1)
type_text("You wade towards the deepest part of the river you can find and scoop up some water into the vial")
print()
time.sleep(1)
if timewasted == True:
    type_text("As you finish collecting the water, you hear a loud roar coming from the forest")
    print()
    time.sleep(1)
    type_text(choice)
    print()
    time.sleep(1)
    print("1. Run away")
    time.sleep(1)
    print("2. Stay and investigate")
    choice8=input()
    if choice8 == "1":
        type_text("You see a large creature slowly emerge from the trees as you run off towards the tree you entered from")
        print()
        time.sleep(1)
        type_text("The creature is massive, with sharp claws and teeth, and it looks very angry")
        print()
        time.sleep(1)
        type_text("As you reach the tree, the creature lets out a deafening roar and charges towards you")
        print()
        time.sleep(1)
        type_text("The creature tackles you to the ground, and you feel its sharp claws digging into your flesh")
        print()
        time.sleep(1)
        type_text("You are barely able to wiggle free and jump through a hole that appears in the tree trunk as you do so")
        print()
        time.sleep(1)
        scars=True
        type_text("As you emerge from the hole, you feel your body aching and you notice several deep scratches on your arms and legs")
        print()
        time.sleep(1)
        type_text("You see that you are back in the robed figure's sanctum")
        print()
        time.sleep(1)
    elif choice8 == "2":
        type_text("You decide to stay and investigate the noise")
        print()
        time.sleep(1)
        type_text("As you move deeper into the forest, you see a large creature emerge from the trees")
        print()
        time.sleep(1)
        type_text("The creature is massive, with sharp claws and teeth, and it looks very angry")
        print()
        time.sleep(1)
        type_text("As it sees you, it suddenly cries out with a deep, guttural sound and charges towards you")
        print()
        time.sleep(1)
        type_text("You try to run, but the creature is too fast and tackles you to the ground")
        print()
        time.sleep(1)
        type_text("You try your best to fight back, but the creature's strength is overwhelming")
        print()
        time.sleep(1)
        type_text("You begin to feel lightheaded and your vision goes dark")
        print()
        time.sleep(1)
        type_text("Game Over")
        sys.exit()
else:
    type_text("You walk back towards the tree and see a hole appearing in the trunk as you approach")
    print()
    time.sleep(1)
    type_text("You step through the hole and see yourself back in the robed figure's sanctum")
    print()
    time.sleep(1)
type_text("To be continued...")