# Copyright (c) 2025 TheEmbersOfTwilight
# Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0) for code.
# Creative assets and prose in this repository are licensed under CC BY-NC-SA 4.0 unless otherwise noted.
# See LICENSE-AGPl-3.0 and LICENSE-CC-BY-NC-SA-4.0 in the repository root for full license texts.
import time
import sys

from core import GameState

game_state = GameState() # create new game state

question = "What do you say?" #Generic question prompt
choice = "What do you do?" #Generic choice prompt
def type_text(text, delay=0.025): #Function to simulate typing effect
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()  
        time.sleep(delay)
type_text("Welcome to 'Warden's Sanctum', a text adventure game")
print()
type_text("When you are given a choice, type the number associated with the option you would like to choose")
print()
time.sleep(2)
type_text("Please do not do so until the options have fully loaded")
print()
time.sleep(2)
type_text("Have a good time!")
print()
time.sleep(5)
type_text("You awaken in a dark, damp room on a grimy bed")
time.sleep(1)
print()
type_text("You see a shelf on the opposite side of the room from where you currently are.")
time.sleep(1)
print()
type_text("As you get up from the bed, you see that it is being held up by chains connected to the wall.")
time.sleep(1)
print()
type_text("You also see that one wall of the room is made of metal bars.")
time.sleep(1)
print()
while not game_state.wand:
    type_text(choice)
    time.sleep(1)
    print()
    print("1. Look through the bars")
    time.sleep(1)
    print("2. Look at the shelf")
    time.sleep(1)
    print("3. Inspect the bed")
    choice1=input()
    if choice1 == "1":
        type_text("You see many cells along the hall on the other side of the bars.")
        print()
        time.sleep(1)
        type_text(choice)
        time.sleep(1)
        print()
        print("1. Call out")
        time.sleep(1)
        print("2. Go back")
        choice2 = input()
        if choice2 == "1": 
            if game_state.callout_counter <50:
                type_text("You call out down the empty halls and get no response")
                time.sleep(1)
                print()
                type_text("You walk back into the cell")
                print()
                time.sleep(1)
                game_state.callout_counter += 1 
                continue
            elif game_state.callout_counter >=50:
                type_text("You call out down the empty halls and hear a louad, deep growl off in the distance")
                time.sleep(1)
                print()
                type_text("You see a large, gruesome creature emerge from the shadows and slowly make its way towards you")
                time.sleep(1)
                print()
                type_text("The creature is massive, with sharp claws and teeth, and it looks very angry")
                time.sleep(1)
                print()
                type_text("As it gets closer, you realize that it is heading straight for you")
                time.sleep(1)
                print()
                type_text("You feel a sharp pain as the creature attacks you, and your vision goes dark")
                time.sleep(1)
                print()
                type_text("Game Over")
                print()
                sys.exit()
        else: 
            type_text("You walk back into the cell")
            print()
            time.sleep(1)
            continue
    elif choice1 == "2": 
        if game_state.razor >= 1:
            if game_state.infinite_razor_counter <20:
                type_text("You look at the shelf and see nothing of interest, you walk back into the middle of the cell")
                print()
                time.sleep(1)
                game_state.infinite_razor_counter += 1
                continue
            elif game_state.infinite_razor_counter >=20:
                type_text("You look at the shelf and see another razor identical to the one you picked up earlier")
                time.sleep(1)
                print()
                type_text("Are you happy now, Lennon?")
                time.sleep(1)
                print()
                type_text(choice)
                time.sleep(1)
                print()
                print("1. Pick up the razor")
                time.sleep(1)
                print("2. Leave it")
                choice3=input()
                if choice3 == "1":
                    time.sleep(1)
                    type_text("You pick up the razor and walk back to the middle of the cell")
                    print()
                    game_state.infinite_razor_counter += 1
                    game_state.razor += 1
                    continue
                else:
                    type_text("You leave it and walk back to the middle of the cell")
                    print()
                    game_state.infinite_razor_counter += 1
                    continue
        else:
            type_text("You look at the shelf and see a dull, old style razor")
            time.sleep(1)
            print()
            type_text(choice)
            time.sleep(1)
            print()
            print("1. Pick up the razor")
            time.sleep(1)
            print("2. Leave it")
            choice3=input()
            if choice3 == "1":
                time.sleep(1)
                type_text("You pick up the razor and walk back to the middle of the cell")
                print()
                game_state.razor=1
                continue
            else:
                type_text("You leave it and walk back to the middle of the cell")
                print()
                continue
    elif choice1 == "3":
        type_text("You inspect the bed closer and see a compartment hidden under the mattress")
        print()
        time.sleep(1)
        type_text("In the compartment you see a stick that tapers near the end, it has complex designs carved into it")
        print()
        time.sleep(1)
        type_text("You feel an aura of energy emanating from it and your fingers tingle as you hold it")
        print()
        time.sleep(1)
        type_text("You walk back into the middle of the cell")
        print()
        time.sleep(1)
        game_state.wand=True
    else:
        continue
type_text("You now see a silhouette of a door on the wall next to the bed")
time.sleep(1)
while not game_state.door1:
    print()
    type_text(choice)
    print()
    time.sleep(1)
    print("1. Inspect the silhouette")
    time.sleep(1)
    print("2. Inspect the stick")
    choice4=input()
    if choice4 == "2":
        type_text("You inspect the stick and see that its designs are reminiscent of those you have seen in drawings of wands in fantasy books")
        time.sleep(1)
        print()
        continue
    elif choice4 == "1":
        type_text("You inspect the silhouette and see that there is a small hole within it that would fit the stick")
        print()
        time.sleep(1)
        type_text("You stick one end of the stick into the hole, it does not work")
        print()
        time.sleep(3)
        type_text("A few seconds later you realize it must be the other side that works, then stick that end in")
        print()
        time.sleep(1)
        type_text("The door swings open and you walk through")
        print()
        time.sleep(1)
        game_state.door1=True
    else:
        continue
type_text("You see a flash of light and your vison goes dark")
print()
time.sleep(3)
type_text("You awake from whatever has affected you, you have no idea how long you've been out but it feels as though it has been a while")
time.sleep(1)
print()
type_text("You see that you are in a room filled with books and beakers of all sorts, many of the beakers are filled with colorful liquids, while others are empty")
print()
time.sleep(1)
while not game_state.potion1:
    type_text(choice)
    print()
    time.sleep(1)
    print("1. Inspect the books")
    time.sleep(1)
    print("2. Inspect the beakers")
    time.sleep(1)
    choice5=input()
    if choice5 == "1":
        type_text("You take a closer look at the books and see a few of interest")
        time.sleep(1)
        print()
        print("The Secrets of Divination")
        time.sleep(1)
        print("The Sorcerer's Handbook of Draughts")
        time.sleep(1)
        print("How To Aid and Keep Thy Friends Forever")
        time.sleep(1)
        type_text("You decide against taking any of them as you feel a strange aura around them")
        print()
        time.sleep(1)
        continue
    elif choice5 == "2":
        type_text("You look closely at the beakers and see that one has a design on the glass identical to the one on the stick")
        print()
        time.sleep(1)
        type_text("It has a strange purple liquid inside that seems to shimmer and move on its own")
        print()
        time.sleep(1)
        type_text("You grab the beaker and pocket it, then hear a strange noise just a few moments later")
        print()
        time.sleep(3)
        game_state.potion1=True
    else:
        continue
type_text("You see a tall, robed figure approach you and loudly bellow")
print()
time.sleep(1)
type_text('"What are you doing in my sanctum?"')
print()
time.sleep(1)
while True:
    type_text(question)
    time.sleep(1)
    print()
    print("1. I'm lost and found this place")
    time.sleep(1)
    print("2. I'm your new apprentice")
    choice6=input()
    if choice6 == "1":
        type_text('"How did you find this place, then? Did you come here from the prison?')
        print()
        time.sleep(1)
        break
    elif choice6 == "2":
        type_text('"I do not remember hiring a new apprentice"')
        print()
        type_text('"You are an imposter!"')
        print()
        time.sleep(1)
        type_text("He chants in a language you cannot understand and you feel light headed, you fall and your mind goes blank.")
        print()
        type_text("Game Over")
        print()
        sys.exit()
    else:
        continue
type_text('"Well then, I will help you for a short while. But you will have to assist me for a time."')
print()
time.sleep(1)
type_text("The man walks you to a small room down a hall that appears as he walks over to the wall where he came from")
print()
time.sleep(1)
type_text("Inside the room is a small bed with what appears to be a down mattress")
print()
time.sleep(1)
type_text("There is also a side table next to the bed and a dresser on the opposite wall")
print()
time.sleep(1)
type_text('"Get some rest, and come talk to me in the morning"')
print()
time.sleep(1)
while True:
    type_text(choice)
    print()
    print("1. Go to sleep")
    print("2. Look in the dresser") 
    print("3. Check the side table")
    choice_room = input()
    if choice_room == "1":
        type_text("You lie down on the bed and quickly fall asleep")
        break
    elif choice_room == "2":
        type_text("The dresser appears to be empty except for some old robes")
        print()
        continue
    elif choice_room == "3":
        type_text("There's nothing but dust on the side table")
        print()
        continue
print()
time.sleep(3)
type_text("You awake the next morning feeling refreshed")
print()
time.sleep(1)
type_text("You get up from the bed and walk out into the main room where the robed figure was")
print()
time.sleep(1)
type_text("You see that he is busy mixing a potion at a large table covered in beakers and books")
print()
time.sleep(1)
while True:
    type_text(choice)
    print()
    print("1. Approach him")
    print("2. Look around the room first")
    choice_morning = input()
    
    if choice_morning == "1":
        type_text("You walk up to the robed figure")
        print()
        break
    elif choice_morning == "2":
        type_text("You see many strange artifacts and bottles, but nothing you understand")
        print()
        continue
type_text("He looks up as you approach and speaks")
print()
time.sleep(1)
type_text('"Ah, you are awake. Good, I have a task for you."')
print()
time.sleep(1)
type_text('"I need you to gather some ingredients for a potion I am working on."')
print()
time.sleep(1)
while True:
    type_text(question)
    print()
    print("1. What kind of potion is it?")
    print("2. What ingredients do you need?")
    print("3. Why should I help you?")
    choice_quest = input() 
    if choice_quest == "1":
        type_text('"That is not your concern for now. Focus on the task at hand."')
        print()
    elif choice_quest == "2":
        break
    elif choice_quest == "3":
        type_text('"Remember, I am helping you. This is a fair exchange."')
        print()    
    else:
        continue
type_text('"First, go to the forest outside and gather some moonshade flowers."')
print()
time.sleep(1)
type_text('"Next, go to the river and collect some water from the deepest part."')
print()
time.sleep(1)
type_text('"Finally, return here and I will show you how to make the potion."')
print()
time.sleep(1)
type_text("He hands you a small bag and a vial")
print()
time.sleep(1)
type_text("He points you towards a door that appears on the wall as he gestures")
print()
time.sleep(1)
type_text('"Go through there to reach the forest."')
print()
time.sleep(1)
while True:
    type_text(choice)
    print()
    print("1. Go through the door")
    print("2. Ask more questions")
    choice_leave = input()
    if choice_leave == "1":
        break
    elif choice_leave == "2":
        type_text('"There is no time for more questions. Go now."')
        print()
    else:
        continue
type_text("You walk through the door and find yourself next to a tree in a dense forest, with a dilapidated stone building off in the distance")
print()
time.sleep(1)
type_text("It appears to be the building that you awoke in earlier")
print()
time.sleep(1)
type_text("You feel a strange pull towards a clearing deeper in the forest")
print()
time.sleep(1)
type_text("You walk towards the clearing, feeling more and more drawn to it with each step")
print()
time.sleep(1)
type_text("As you approach the clearing, the pull suddenly fades away")
print()
time.sleep(1)
type_text("In the center of the clearing, you see a patch of glowing flowers")
print()
time.sleep(1)
type_text("You walk over to the flowers and see that they are indeed moonshade flowers")
print()
time.sleep(1)
type_text("You move closer and inspect them closely")
print()
time.sleep(1)
type_text("Their stems seem to be incredibly thick and sturdy, almost like vines")
print()
time.sleep(1)
type_text("You get the feeling that you cannot pick them without using some sort of sharp object or ripping them out by the roots")
print()
time.sleep(1)
while True:
    type_text(choice)
    print()
    time.sleep(1)
    print("1. Pick the flowers")
    time.sleep(1)
    print("2. Leave empty handed")
    time.sleep(1)
    choice7=input()
    if choice7 == "1":
        if game_state.razor == 1:
            type_text("You remember the razor you picked up earlier")
            print()
            time.sleep(1)
            type_text("You use the razor to carefully cut the flowers from their stems, being careful not to damage them")
            print()
            time.sleep(1)
            type_text("You gather a small bouquet of the flowers")
            print()
            time.sleep(1)
            type_text("As you collect the final flower, your razor snaps in half from the strain")
            print()
            time.sleep(1)
            game_state.razor -= 1
            game_state.flowers_collected=True
            break
        else:
            type_text("You try to pick the flowers by hand, but their stems are too thick and sturdy to break")
            print()
            time.sleep(1)
            type_text("After several frustrating minutes, you are finally able to rip a few flowers free")
            print()
            time.sleep(1)
            game_state.timewasted=True
            game_state.flowers_collected=True
            break
    elif choice7 == "2":
        type_text("You decide to leave the flowers alone")
        print()
        time.sleep(1)
        game_state.flowers_collected=False
        break
    else:
        continue
type_text("You head towards the stone building")
print()
time.sleep(1)
type_text("It has a similar pull to the clearing, but not as strong")
print()
time.sleep(1)
type_text("As you approach the building, you see that there is a small river running alongside it")
print()
time.sleep(1)
type_text("You walk over to the river and see that it is quite deep in the center")
print()
time.sleep(1)
type_text("You wade into the river, thinking about how this must be the river the robed figure mentioned")
print()
time.sleep(1)
while True:
    type_text(choice)
    print()
    time.sleep(1)
    print("1. Collect water from the river")
    time.sleep(1)
    print("2. Leave the river")
    time.sleep(1)
    choice9=input()
    if choice9 == "1":
        type_text("You wade towards the deepest part of the river you can find and scoop up some water into the vial")
        print()
        time.sleep(1)
        game_state.water_collected=True
        if game_state.timewasted:
            type_text("As you finish collecting the water, you hear a loud roar coming from the forest")
            print()
            time.sleep(1)
            type_text(choice)
            print()
            time.sleep(1)
            print("1. Run away")
            time.sleep(1)
            print("2. Stay and investigate")
            choice8=input()
            if choice8 == "1":
                type_text("You see a large creature slowly emerge from the trees as you run off towards the tree you entered from")
                print()
                time.sleep(1)
                type_text("The creature is massive, with sharp claws and teeth, and it looks very angry")
                print()
                time.sleep(1)
                type_text("As you reach the tree, the creature lets out a deafening roar and charges towards you")
                print()
                time.sleep(1)
                type_text("The creature tackles you to the ground, and you feel its sharp claws digging into your flesh")
                print()
                time.sleep(1)
                type_text("You are barely able to wiggle free and jump through a hole that appears in the tree trunk as you do so")
                print()
                time.sleep(1)
                game_state.scars=True
                type_text("As you emerge from the hole, you feel your body aching and you notice several deep scratches on your arms and legs")
                print()
                time.sleep(1)
                type_text("You see that you are back in the robed figure's sanctum")
                print()
                time.sleep(1)
                break
            elif choice8 == "2":
                type_text("You decide to stay and investigate the noise")
                print()
                time.sleep(1)
                type_text("As you move deeper into the forest, you see a large creature emerge from the trees")
                print()
                time.sleep(1)
                type_text("The creature is massive, with sharp claws and teeth, and it looks very angry")
                print()
                time.sleep(1)
                type_text("As it sees you, it suddenly cries out with a deep, guttural sound and charges towards you")
                print()
                time.sleep(1)
                type_text("You try to run, but the creature is too fast and tackles you to the ground")
                print()
                time.sleep(1)
                type_text("You try your best to fight back, but the creature's strength is overwhelming")
                print()
                time.sleep(1)
                type_text("You begin to feel lightheaded and your vision goes dark")
                print()
                time.sleep(1)
                type_text("Game Over")
                sys.exit()
        else: 
            type_text("You walk back towards the tree and see a hole appearing in the trunk as you approach")
            print()
            time.sleep(1)
            break
    elif choice9 == "2":
        type_text("You walk back towards the tree and see a hole appearing in the trunk as you approach")
        print()
        time.sleep(1)
        break
    else:
        continue
while True:
    type_text(choice)
    print()
    time.sleep(1)  
    print("1. Enter the hole in the tree")
    time.sleep(1)
    print("2. Stay outside")
    choice_tree=input()
    if choice_tree == "1":
        if game_state.flowers_collected and game_state.water_collected:
            type_text("You walk back into the sanctum and approach the robed figure")
            print()
            time.sleep(1)
            type_text('"Ah, you have returned. Do you have the ingredients?"')
            print()
            time.sleep(1)
            type_text("You show him the flowers and the vial of water")
            print()
            time.sleep(1)
            type_text('"Excellent work. Now, watch closely as I show you how to make the potion."')
            print()
            time.sleep(1)
            type_text("He begins to mix the ingredients together in a large beaker, chanting softly under his breath")
            print()
            time.sleep(1)
            game_state.flowers_collected=False
            game_state.water_collected=False
            type_text("As he works, you feel a strange energy building in the room")
            print()
            time.sleep(1)
            type_text("Finally, he finishes the potion and hands it to you")
            print()
            time.sleep(1)
            type_text('"Here, take this potion. It will grant you great power, but use it wisely."')
            print()
            time.sleep(1)
            type_text("You take the potion and feel a surge of energy coursing through your body")
            print()
            time.sleep(1)
            game_state.powerupgraded=1
            if game_state.scars:
                type_text("The scratches on your arms and legs begin to heal rapidly, leaving behind faint scars as a reminder of your encounter in the forest")
                print()
                time.sleep(1)
                game_state.scars=False
        elif not game_state.flowers_collected and not game_state.water_collected:
            type_text('"You have returned empty handed. I am disappointed."')
            print()
            time.sleep(1)
            type_text("He chants in a language you cannot understand and you feel light headed, you fall and your mind goes blank.")
            print()
            time.sleep(1)
            type_text("Game Over")
            print()
            sys.exit()
        elif game_state.flowers_collected and game_state.water_collected:
            type_text('"You did not gather the flowers. This is unacceptable."')
            print()
            time.sleep(1)
            type_text("He chants in a language you cannot understand and you feel light headed, you fall and your mind goes blank.")
            print()
            time.sleep(1)
            type_text("Game Over")
            print()
            sys.exit()
        elif game_state.flowers_collected and not game_state.water_collected:
            type_text('"You did not gather the water. This is unacceptable."')
            print()
            time.sleep(1)
            type_text("He chants in a language you cannot understand and you feel light headed, you fall and your mind goes blank.")
            print()
            time.sleep(1)
            type_text("Game Over")
            print()
            sys.exit()
        type_text('"I will allow you to leave, but first, you must prove your worth."')
        print()
        time.sleep(1)
        type_text('"Get through my labrinth alive, and you may go free."')
        print()
        time.sleep(1)
        type_text("A door appears on the wall as he finishes speaking")
        print()
        time.sleep(1)
        type_text("You walk through the door and find yourself in a dark maze")
        print()
        time.sleep(1)
        type_text("You can hear strange noises coming from all around you")
        print()
        time.sleep(1)
        type_text("You see that there are three paths in front of you")
        print()
        time.sleep(1)
        type_text("One path is lit by torches, another is shrouded in darkness, and the last is filled with strange, glowing plants")
        print()
        time.sleep(1)
        while True:
            type_text(choice)
            print()
            time.sleep(1)
            print("1. Take the torchlit path")
            time.sleep(1)
            print("2. Take the dark path")
            time.sleep(1)
            print("3. Take the glowing plant path")
            time.sleep(1)
            choice10=input()
            if choice10 == "1":
                type_text("You walk down the path lit by torches")
                print()
                time.sleep(1)
                type_text("As you walk, you feel a strange presence following you")
                print()
                time.sleep(1)
                type_text("You see shadows moving above you and hear whispers in your ear")
                print()
                time.sleep(1)
                type_text("You see a small, dark creature jump down from the ceiling in front of you")
                print()
                time.sleep(1)
                type_text("The creature is about a foot shorter that you, with sharp claws and teeth, and glowing red eyes")
                print()
                time.sleep(1)
                type_text("Its eyes suddenly lose their glow and the creature's teeth and claws retract, revealing a small, timid looking animal")
                print()
                time.sleep(1)
                type_text("The creature looks up at you with big, pleading eyes")
                print()
                time.sleep(1)
                while True:
                    type_text(choice)
                    print()
                    time.sleep(1)
                    print("1. Help the creature")
                    time.sleep(1)
                    print("2. Ignore the creature and keep walking")
                    choice11=input()
                    if choice11 == "1":
                        type_text("You decide to help the creature")
                        print()
                        time.sleep(1)
                        type_text("You pick it up and carry it with you as you walk through the maze")
                        print()
                        time.sleep(1)
                        type_text("After a while, you see a light in the distance")
                        print()
                        time.sleep(1)
                        type_text("The creature jumps out mof your arms and its eyes begin to glow again") 
                        print()
                        time.sleep(1)
                        type_text("It runs towards the light and disappears")
                        print()
                        time.sleep(1)
                        type_text("The light disappears moments later, and the torches around you extinguish")
                        print()
                        time.sleep(1)
                        type_text("You hear as deep rumbling and the walls around you begin to shake")
                        print()
                        time.sleep(1)
                        while True:
                            type_text(choice)
                            print()
                            time.sleep(1)
                            print("1. Run")
                            time.sleep(1)
                            print("2. Stand your ground")
                            choice12=input()
                            if choice12 == "1":
                                type_text("You run as fast as you can back through the maze")
                                print()
                                time.sleep(1)
                                type_text("After what feels like an eternity, you see the point where you entered the maze")
                                print()
                                time.sleep(1)
                                type_text("Right before you reach it, a large piece of debris falls from above and blocks your path")
                                print()
                                time.sleep(1)
                                type_text("You turn around and see that the entire maze is collapsing in on itself")
                                print()
                                time.sleep(1)
                                type_text("A large piece of debris falls from above and hits you")
                                print()
                                time.sleep(1)
                                type_text("Game Over")
                                print()
                                sys.exit()
                            elif choice12 == "2":
                                type_text("You stand your ground as the walls around you begin to shake violently")
                                print()
                                time.sleep(1)
                                type_text("The walls collapse in on you, and you are buried under the rubble")
                                print()
                                time.sleep(1)
                                type_text("Game Over")
                                print()
                                sys.exit()
                            else:
                                continue
                    elif choice11 == "2":
                        type_text("You decide to ignore the creature and keep walking")
                        print()
                        time.sleep(1)
                        type_text("As you walk, you feel a sharp pain in your back")
                        print()
                        time.sleep(1)
                        type_text("You turn around and see the creature biting into your back with its sharp teeth")
                        print()
                        time.sleep(1)
                        type_text("You try to shake it off, but it is too strong")
                        print()
                        time.sleep(1)
                        type_text("You feel yourself losing consciousness as the creature continues to bite into you")
                        print()
                        time.sleep(1)
                        type_text("Game Over")
                        print()
                        sys.exit()
                    else:
                        continue
            elif choice10 == "2":
                type_text("You walk down the dark path")
                print()
                time.sleep(1)
                type_text("As you walk, you feel a cold breeze and hear strange whispers all around you")
                print()
                time.sleep(1)
                type_text("Suddenly, you see a pair of glowing eyes staring at you from the darkness")
                print()
                time.sleep(1)
                type_text("A shadowy figure emerges from the darkness, its eyes glowing with an eerie light")
                print()
                time.sleep(1)
                type_text("The figure approaches you slowly, its movements fluid and unnatural")
                print()
                time.sleep(1)
                type_text("As it gets closer, you can see that it is a tall, slender humanoid creature with long, sharp claws and teeth")
                print()
                time.sleep(1)
                type_text("The creature lets out a low growl and lunges at you")
                print()
                time.sleep(1)
                type_text("You try to dodge its attack, but it is too fast")
                print()
                time.sleep(1)
                type_text("The creature sinks its claws into your flesh, and you feel a searing pain as it rips into you")
                print()
                time.sleep(1)
                type_text("You try to fight back, but the creature's strength is overwhelming")
                print()
                time.sleep(1)
                type_text("You begin to feel lightheaded and your vision goes dark")
                print()
                time.sleep(1)
                type_text("Game Over")
                print()
                sys.exit()
            elif choice10 == "3":
                type_text("You walk down the path filled with glowing plants")
                print()
                time.sleep(1)
                type_text("As you walk, you feel a strange sensation in your body")
                print()
                time.sleep(1)
                type_text("The plants around you begin to glow brighter and brighter, until the entire path is bathed in a soft, ethereal light")
                print()
                time.sleep(1)
                type_text("You feel a warmth spreading through your body, and you begin to feel more powerful and energized")
                print()
                time.sleep(1)
                game_state.powerupgraded += 1
                type_text("You continue down the path, feeling stronger and more confident with each step")
                print()
                time.sleep(1)
                type_text("You see a particularly large and vibrant plant up ahead")
                print()
                time.sleep(1)
                while True:
                    type_text(choice)
                    print()
                    time.sleep(1)
                    print("1. Inspect the plant")
                    time.sleep(1)
                    print("2. Ignore the plant and keep walking")
                    choice13=input()
                    if choice13 == "1":
                        type_text("You walk over to the plant and inspect it closely")
                        print()
                        time.sleep(1)
                        type_text("As you touch the plant, you feel a sharp pain on your back")
                        print()
                        time.sleep(1)
                        type_text("You turn around and see that the plant has sprouted several sharp thorns that have pierced your skin")
                        print()
                        time.sleep(1)
                        type_text("You try to pull the thorns out, but they are deeply embedded in your flesh")
                        print()
                        time.sleep(1)
                        game_state.scars=True
                        type_text("You are able to get away from the plant and slowly remove the thorns, but not before they leave behind several deep scratches on your back")
                        print()
                        time.sleep(1)
                        type_text("You continue down the path, feeling the scratches sting with each step")
                        break
                    elif choice13 == "2":
                        type_text("You decide to ignore the plant and keep walking")
                        print()
                        time.sleep(1)
                        break
                    else:
                        continue
                type_text("After a while, you see a light in the distance")
                print()
                time.sleep(1)
                type_text("You walk towards the light and see that it is the exit of the maze")
                print()
                time.sleep(1)
                type_text("You step through the exit and find yourself back in the robed figure's sanctum")
                print()
                time.sleep(1)
                break
            else:
                continue
        type_text("You approach the robed figure")
        print()
        time.sleep(1)
        type_text('"You have proven your worth. You may go free."')
        print()
        time.sleep(1)
        type_text("A door appears on the wall as he finishes speaking")
        print()
        time.sleep(1)
        type_text("You walk through the door and find yourself outside, free at last")
        print()
        time.sleep(1)
        type_text("You find yourself in a wide open field on the top of a hill, with a clear view of the sunrise in the distance")
        print()
        time.sleep(1)
        type_text("You sit down on the grass and watch as the sun rises over the horizon, feeling a sense of peace and freedom wash over you")
        print()
        time.sleep(10)
        type_text("After a short while, you see a figure approaching you from the distance")
        print()
        time.sleep(1)
        type_text("As the figure gets closer, you see that it is a person holding a map and a compass")
        print()
        time.sleep(1)
        type_text("The person approaches you and speaks")
        print()
        time.sleep(1)
        type_text('"Hello there, traveler"')
        print()
        time.sleep(1)
        type_text('"You look like you have been through quite an adventure"')
        if game_state.scars:
            type_text("They notice the scars on your arms and legs and raise an eyebrow")
            print()
            time.sleep(1)
            type_text('"Those look painful, what happened to you?"')
            print()
            time.sleep(1)
            type_text("You tell them about your encounter and how you barely escaped with your life")
            print()
            time.sleep(1)
            type_text('"Wow, that sounds intense. You must be quite the survivor."')
            print()
            time.sleep(1)
        type_text('"I am heading for the next town over, would you like to join me?"')
        print()
        time.sleep(1)
        type_text("You nod and stand up, ready to continue your journey")
        print()
        time.sleep(1)
        break
    elif choice_tree == "2":
        type_text("You decide to stay outside the tree")
        print()
        time.sleep(1)
        type_text("You wander the forest for hours, trying to find a way out")
        print()
        time.sleep(1)
        type_text("As night falls, you realize that you are hopelessly lost")
        print()
        time.sleep(1)
        type_text("You hear strange noises all around you and feel a cold breeze on your skin")
        print()
        time.sleep(1)
        type_text("Suddenly, you see a pair of glowing eyes staring at you from the darkness")
        print()
        time.sleep(1)
        type_text("A shadowy figure emerges from the darkness, its eyes glowing with an eerie light")
        print()
        time.sleep(1)
        type_text("The figure approaches you slowly, its movements fluid and unnatural")
        print()
        time.sleep(1)
        type_text("As it gets closer, you can see that it is a tall, slender humanoid creature with long, sharp claws and teeth")
        print()
        time.sleep(1)
        type_text("The creature lets out a low growl and lunges at you")
        print()
        time.sleep(1)
        type_text("You try to dodge its attack, but it is too fast")
        print()
        time.sleep(1)
        type_text("The creature sinks its claws into your flesh, and you feel a searing pain as it rips into you")
        print()
        time.sleep(1)
        type_text("You try to fight back, but the creature's strength is overwhelming")
        print()
        time.sleep(1)
        type_text("You begin to feel lightheaded and your vision goes dark")
        print()
        time.sleep(1)
        type_text("Game Over")
        print()
        sys.exit()
    else:
        continue
type_text("You and the traveler set off towards the town")
print()
time.sleep(1)
type_text("As you walk, the traveller turns to talk to you")
print()
time.sleep(1)
type_text('"So, what brings you out here?"')
print()
time.sleep(1)
type_text("You tell them about your time in the warden's anctum and the trials you faced")
print()
time.sleep(1)
type_text('"I have had my fair share of troubles too."')
print()
time.sleep(1)
type_text('"But it seems we both made it through."')
print()
time.sleep(1)
type_text("After a while, you see the town in the distance")
print()
time.sleep(1)
type_text("You and the traveler make your way into the town")
print()
time.sleep(1)
type_text('"I am going to head to the inn to rest. Would you like to join me?"')
print()
time.sleep(1)
while True:
    type_text(question)
    print()
    time.sleep(1)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    choice14=input()
    if choice14 == "1":
        type_text("You and the traveler head to the inn together")
        print()
        time.sleep(1)
        type_text("You share a room and sleep the night")
        print()
        time.sleep(1)
        game_state.day_night_cycle=0
        break
    elif choice14 == "2":
        type_text("You decide against it and walk into the town alone")
        print()
        time.sleep(1)
        game_state.day_night_cycle=1
        while True:
            type_text(choice)
            print()
            time.sleep(1)
            print("1. Look around the town")
            time.sleep(1)
            print("2. Talk to the locals")
            time.sleep(1)
            print("3. Go to the inn")
            choice15=input()
            if choice15 == "1":
                type_text("You walk around the town, taking in the sights and sounds")
                print()
                time.sleep(1)
                type_text("You see a market square filled with vendors selling all sorts of goods")
                print()
                time.sleep(1)
                type_text("You also see a tavern where people are drinking and socializing")
                print()
                time.sleep(1)
                continue
            elif choice15 == "2":
                type_text("You approach a group of locals and strike up a conversation")
                print()
                time.sleep(1)
                type_text("They tell you about the town and its history, as well as some of the local legends")
                print()
                time.sleep(1)
                type_text("You learn about a hidden treasure that is said to be buried somewhere in the town")
                print()
                time.sleep(1)
                type_text("They also warn you about a dangerous creature that is said to roam the outskirts of the town at night")
                print()
                time.sleep(1)
                Town1nfo=True
                continue
            elif choice15 == "3":
                type_text("You head to the inn")
                print()
                time.sleep(1)
                type_text("You sleep the night")
                print()
                time.sleep(1)
                game_state.day_night_cycle=0
                break
    else:
        continue
type_text("You wake up the next morning, feeling refreshed and ready to continue your journey")
print()
time.sleep(1)  
type_text("You step outside the inn and see the bustling town around you")
print()
time.sleep(1)  
type_text("The sun is shining and the birds are singing")
print()
time.sleep(1)  
type_text("You take a deep breath and prepare to face whatever challenges lie ahead")
print()
time.sleep(1)  
type_text("As you stand there, taking in the sights and sounds of the town, you see a figure approaching you from the distance")
print()
time.sleep(1)
type_text("As they come closer, you see that they have a long cloak and a wide-brimmed hat that obscures their face")
print()
time.sleep(1)
while True:
    type_text(choice)
    print()
    time.sleep(1)
    print("1. Greet the figure")
    time.sleep(1)
    print("2. Ignore the figure")
    choice16=input()
    if choice16 == "1":
        type_text("You greet the figure as they approach you")
        print()
        time.sleep(1)
        break
    elif choice16 == "2":
        type_text("You decide to ignore the figure and continue on your way")
        print()
        time.sleep(1)
        type_text("As you walk away, you hear the figure call out to you")
        print()
        time.sleep(1)
        type_text('"Hey, wait up!"')
        print()
        time.sleep(1)
        type_text("You turn around and see the figure approaching you")
        print()
        time.sleep(1)
        break
    else:
        continue
type_text("The figure stops in front of you and pulls back their hood, revealing a friendly face")
print()
time.sleep(1)
type_text('"Greetings, I am Arin. I just came into town and was wondering if you could help me out."')
print()
time.sleep(1)
type_text('"I am looking for someone to guide me to the old ruins outside of town. Would you be interested?"')
print()
time.sleep(1)
while True:
    type_text(question)
    print()
    time.sleep(1)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    choice17=input()
    if choice17 == "1":
        type_text("You agree to help Arin find the old ruins")
        print()
        time.sleep(1)
        type_text('"Great! You will be greatly rewarded for your kindness."')
        print()
        time.sleep(1)
        type_text("You and Arin set off towards the old ruins outside of town")
        print()
        time.sleep(1)
        type_text("As you walk, Arin tells you about their quest to find a powerful artifact hidden within the ruins")
        print()
        time.sleep(1)
        type_text("You navigate through the dense forest and rocky terrain, eventually reaching the entrance to the ruins")
        print()
        time.sleep(1)
        type_text("You and Arin enter the ruins")
        print()
        time.sleep(1)
        type_text('"I believe the artifact is located in the main chamber. Let\'s head there."')
        print()
        time.sleep(1)
        type_text("You follow Arin through the winding corridors of the ruins, until you come across a large chamber filled with ancient artifacts and treasures")
        print()
        time.sleep(1)
        type_text("In the center of the chamber, you see a pedestal with a glowing object resting on top of it")
        print()
        time.sleep(1)
        type_text("Arin approaches the pedestal and picks up the artifact")
        print()
        time.sleep(1)
        type_text('"We did it! This artifact will be invaluable to my rise to power."')
        print()
        time.sleep(1)
        type_text("You watch as Arin grabs the artifact and a bright light envelops them")
        print()
        time.sleep(1)
        type_text("When the light fades, you see that Arin has transformed into a powerful being, radiating with energy")
        print()
        time.sleep(1)
        type_text('"Thank you for helping me achieve my destiny. I could not have done it without you."')
        print()
        time.sleep(1)
        type_text('"Now I musn\'t leave any witnesses."')
        print()
        time.sleep(1)
        type_text("Before you can react, Arin unleashes a powerful blast of energy that hits you square in the chest")
        print()
        time.sleep(1)
        type_text("You feel yourself being lifted off the ground as the energy courses through your body")
        print()
        time.sleep(1)
        type_text("Your vision goes dark as you lose consciousness")
        print()
        time.sleep(5)
        game_state.arins_rise=True
        game_state.scars=True
        game_state.powerupgraded -= 1
        if game_state.powerupgraded < 0:
            game_state.powerupgraded=0
        game_state.day_night_cycle=1
        type_text("You awaken hours later, lying on the ground in the ruins")
        print()
        time.sleep(1)
        type_text("You feel weak and disoriented, but you are alive")
        print()
        time.sleep(1)
        type_text("You see that your body is covered in scars from the blast of energy")
        print()
        time.sleep(1)
        type_text("You slowly get to your feet and make your way out of the ruins")
        print()
        time.sleep(1)
        type_text("As you exit the ruins, you see that the sun is setting in the distance")
        print()
        time.sleep(1)
        type_text("You make your way back to the town, feeling grateful to be alive")
        print()
        time.sleep(1)
        break
    elif choice17 == "2":
        type_text("You politely decline Arin's request for help")
        print()
        time.sleep(1)
        type_text('"No worries, I understand. Maybe another time."')
        print()
        time.sleep(1)
        type_text("Arin nods and walks away, disappearing into the crowd of people in the town square")
        print()
        time.sleep(1)
        break
    else:
        continue
if game_state.arins_rise:
    while True:
        type_text(choice)
        print()
        time.sleep(1)
        print("1. Go to the inn to rest")
        time.sleep(1)
        print("2. Explore the town")
        choice18=input()
        if choice18 == "1":
            type_text("You head to the inn to rest for the night")
            print()
            time.sleep(1)
            type_text("You sleep the night, feeling exhausted from your encounter with Arin")
            print()
            time.sleep(1)
            game_state.day_night_cycle=0
            break
        elif choice18 == "2":
            type_text("You decide to explore the town further")
            print()
            time.sleep(1)
            type_text("As you walk through the streets, you hear whispers and murmurs from the townspeople")
            print()
            time.sleep(1)
            type_text("You soon realize that they are talking about Arin and their sudden rise to power")
            print()
            time.sleep(1)
            type_text("Some people seem fearful, while others are in awe of Arin's newfound strength")
            print()
            time.sleep(1)
            type_text("You feel a sense of unease as you realize that Arin's rise to power may have consequences for the town and its people")
            print()
            time.sleep(1)
            continue
        else:
            continue
else:
    while True:
        type_text(choice)
        print()
        time.sleep(1)
        print("1. Go to the inn to rest")
        time.sleep(1)
        print("2. Explore the town")
        choice19=input()
        if choice19 == "1":
            type_text("You head to the inn to rest for the night")
            print()
            time.sleep(1)
            type_text("You sleep the night, feeling refreshed and ready to continue your journey")
            print()
            time.sleep(1)
            game_state.day_night_cycle=0
            break
        elif choice19 == "2":
            type_text("You decide to explore the town further")
            print()
            time.sleep(1)
            type_text("As you walk through the streets, you see people going about their daily lives, unaware of the dangers that lurk outside the town's walls")
            print()
            time.sleep(1)
            type_text("You feel a sense of peace and safety within the town, but you know that you must eventually leave and face whatever challenges lie ahead")
            print()
            time.sleep(1)
            continue
        else:
            continue
type_text("You wake up the next morining and walk into the inn's dining area, when the innkeeper approaches you")
print()
time.sleep(1)
type_text('"Good morning, traveler. I hope you slept well."')
print()
time.sleep(1)  
type_text('"By the way, there have been some strange happenings in town lately. People have been disappearing without a trace."')
print()
time.sleep(1)  
type_text('"I hear that you have some experience dealing with dangerous situations. Would you be willing to help us figure out what is going on?"')
print()
time.sleep(1)
while True:
    type_text(question)
    print()
    time.sleep(1)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    choice20=input()
    if choice20 == "1":
        type_text("You agree to help the innkeeper investigate the disappearances")
        print()
        time.sleep(1)
        type_text('"Thank you, traveler. We could use all the help we can get."')
        print()
        time.sleep(1)
        type_text("To be continued...")
        #Continue here
        break
    elif choice20 == "2":
        type_text("You politely decline the innkeeper's request for help")
        print()
        time.sleep(1)
        type_text('"I understand. Stay safe out there, traveler."')
        print()
        time.sleep(1)
        type_text("To be continued...")
        #Continue here
        break
    else:
        continue
